http:
  middlewares:

    public-chain:
      chain:
        middlewares:
          - security-headers
          - api-ratelimit

    internal-chain:
      chain:
        middlewares:
          - security-headers
          - api-ratelimit
          - api-auth
