tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/localhost+3.pem
        keyFile: /etc/traefik/certs/localhost+3-key.pem

  certificates:
    - certFile: /etc/traefik/certs/localhost+3.pem
      keyFile: /etc/traefik/certs/localhost+3-key.pem
