global:
  scrape_interval: 15s
  evaluation_interval: 15s

# ==========================
# Alertmanager
# ==========================

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# ==========================
# Alert Rules
# ==========================

rule_files:
  - alerts.yml

# ==========================
# Scrape Jobs
# ==========================

scrape_configs:

  # --------------------------
  # Prometheus
  # --------------------------
  - job_name: "prometheus"
    static_configs:
      - targets:
          - localhost:9090

  # --------------------------
  # cAdvisor
  # --------------------------
  - job_name: "cadvisor"
    scrape_interval: 30s
    scrape_timeout: 25s
    static_configs:
      - targets:
          - cadvisor:8080

  # --------------------------
  # Backend APIs
  # --------------------------
  - job_name: "backend"
    metrics_path: /metrics
    static_configs:
      - targets:
          - backend1:4000
          - backend2:4000

  # --------------------------
  # MySQL Primary Exporter
  # --------------------------
  - job_name: "mysql-primary"
    static_configs:
      - targets:
          - mysqld-exporter-primary:9104

  # --------------------------
  # MySQL Replica Exporter
  # --------------------------
  - job_name: "mysql-replica"
    static_configs:
      - targets:
          - mysqld-exporter-replica:9104

  # --------------------------
  # HAProxy
  # --------------------------
  - job_name: "haproxy"
    metrics_path: /metrics
    static_configs:
      - targets:
          - mysql-router:8404

  # --------------------------
  # Node Exporter
  # --------------------------
  - job_name: "node"
    static_configs:
      - targets:
          - node-exporter:9100

  # --------------------------
  # Redis Exporter
  # --------------------------
  - job_name: "redis"
    static_configs:
      - targets:
          - redis-exporter:9121

  # --------------------------
  # Traefik
  # --------------------------
  - job_name: "traefik"
    metrics_path: /metrics
    static_configs:
      - targets:
          - traefik:8080

  # --------------------------
  # Alertmanager
  # --------------------------
  - job_name: "alertmanager"
    static_configs:
      - targets:
          - alertmanager:9093

  # --------------------------
  # Loki
  # --------------------------
  - job_name: "loki"
    metrics_path: /metrics
    static_configs:
      - targets:
          - loki:3100

  # --------------------------
  # Promtail
  # --------------------------
  - job_name: "promtail"
    metrics_path: /metrics
    static_configs:
      - targets:
          - promtail:9080
